#ifndef INCLUDE_CONFIG_HPP_
#define INCLUDE_CONFIG_HPP_

#define LOGGER_PREFIX_INFO		"[INFO]"
#define LOGGER_PREFIX_WARN		"[WARN]"
#define LOGGER_PREFIX_ERROR		"[ERRO]"

#define CTRLLOOP_FREQ			100
#define CTRLLOOP_PERIOD			1000000 / CTRLLOOP_FREQ

#endif
